# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zakupki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now=True)),
                ('company', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('col', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_sel', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manager', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
