# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zakupki', '0002_auto_20170307_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakupki',
            options={'verbose_name': 'Закупкf', 'verbose_name_plural': 'Закупки'},
        ),
    ]
