# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dostavka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dostavka',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dostavka',
            name='adress',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='dostavka',
            name='company',
            field=models.CharField(max_length=50, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='dostavka',
            name='data_dostavki',
            field=models.DateField(verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='dostavka',
            name='manager',
            field=models.CharField(max_length=30, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='dostavka',
            name='note',
            field=models.TextField(verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='dostavka',
            name='score',
            field=models.CharField(max_length=20, verbose_name='Счет'),
        ),
    ]
